CREATE TABLE IF NOT EXISTS users (
    key VARCHAR(250) NOT NULL PRIMARY KEY,
    value JSONB NOT NULL
);

CREATE TABLE IF NOT EXISTS roles (
    key VARCHAR(250) NOT NULL PRIMARY KEY,
    value JSONB NOT NULL
);

CREATE TABLE IF NOT EXISTS bindings (
    key VARCHAR(250) NOT NULL PRIMARY KEY,
    value JSONB NOT NULL
);
